# Generated by Django 4.0.3 on 2022-05-10 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='grup',
        ),
        migrations.AddField(
            model_name='users',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='users',
            name='edu',
            field=models.SmallIntegerField(choices=[(1, 'Yozildi'), (2, 'Kutmoqda'), (3, 'Guruh_ochildi'), (4, 'Uqiydi')], default=1),
            preserve_default=False,
        ),
    ]
