# Generated by Django 4.0.3 on 2022-05-11 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_users_grup_users_created_date_users_edu'),
    ]

    operations = [
        migrations.AddField(
            model_name='grup',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oy', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.month')),
            ],
        ),
        migrations.AddField(
            model_name='grup',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.month'),
        ),
        migrations.AlterField(
            model_name='pyment',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.month'),
        ),
    ]
