# Generated by Django 4.0.3 on 2022-05-12 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_grup_created_date_month_grup_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='day',
        ),
        migrations.RemoveField(
            model_name='month',
            name='parent',
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('month', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.month')),
            ],
        ),
    ]
